name: Publish
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: windows-latest
    outputs:
      AssemblySemVer: ${{ steps.gitversion.outputs.AssemblySemVer }}
      AssemblySemFileVer: ${{ steps.gitversion.outputs.AssemblySemFileVer }}
      InformationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
      PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}
      Sha: ${{ steps.gitversion.outputs.Sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@main
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@main
  publish:
    runs-on: windows-latest
    needs: calculate-version
    env:
      AssemblySemVer: ${{ needs.calculate-version.outputs.AssemblySemVer }}
      AssemblySemFileVer: ${{ needs.calculate-version.outputs.AssemblySemFileVer }}
      InformationalVersion: ${{ needs.calculate-version.outputs.InformationalVersion }}
      SemVer: ${{ needs.calculate-version.outputs.SemVer }}
      Sha: ${{ needs.calculate-version.outputs.Sha }}
      PlatformTarget: ''
    strategy:
      matrix:
        target: [WindowsDX, UniversalGL, WindowsGL, WindowsXNA]
        configuration: [Release, Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ env.Sha }}
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.x.x'
    - name: Pack
      run: dotnet pack Rampastring.XNAUI.csproj -c ${{ matrix.target }}${{ matrix.configuration }} ${{ env.target == 'WindowsXNA' && '-p:PlatformTarget=x86' || '' }} -p:AssemblyVersion=$env:GitVersion_AssemblySemVer -p:FileVersion=$env:GitVersion_AssemblySemFileVer -p:InformationalVersion=$env:GitVersion_InformationalVersion -p:PackageVersion=$env:GitVersion_NuGetVersionV2
    - name: Upload Artifacts
      uses: actions/upload-artifact@main
      with:
        path: bin\*\*.*nupkg
        if-no-files-found: error
  release:
    needs: [calculate-version, publish]
    env:
      PreReleaseTag: ${{ needs.calculate-version.outputs.PreReleaseTag }}
      SemVer: ${{ needs.calculate-version.outputs.SemVer }}
      Sha: ${{ needs.calculate-version.outputs.Sha }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ env.Sha }}
    - name: Download Artifacts
      uses: actions/download-artifact@main
      with:
        path: ./artifacts
    - name: Release
      run: gh release create v${{ env.SemVer }} (Get-Item artifacts\*.*nupkg) --generate-notes --target ${{ env.Sha }} ${{ env.PreReleaseTag != '' && '--prerelease' || '' }}
      env:
        GH_TOKEN: ${{ github.token }}